export default {
  search: 'Search',
  input: {
    placeholder: 'Search city',
  },
  feel: 'Feel like',
  wind: 'Wind',
  speed: 'm/s',
  humid: 'Humidity',
  lat: 'Latitude',
  lon: 'Longitude',
  weekday: [
    ['Sunday', 'Sun'],
    ['Monday', 'Mon'],
    ['Tuesday', 'Tus'],
    ['Wednesday', 'Wed'],
    ['Thursday', 'Ths'],
    ['Friday', 'Fri'],
    ['Saturday', 'Sat'],
  ],
  month: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  command: {
    louder: 'sound up',
    quieter: 'sound down',
    weather: 'weather',
    photo: 'photo',
    temperature: 'temperature',
    language: 'language',
  },
};
